version: "2.3"
services:
  db:
    image: postgres:13.6
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "pwd1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
    ports:
      - 8000:8000
    command: bash -c "
      ./wait-for-postgres.sh db
      && python3 app/db/create_db.py
      && python3 app/main.py
      "
    depends_on:
      - db